### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by Ataide-Araujo** [ViniciusII/My_ETL#1]
- [x] Tratar inteiros seguidos ou antecedidos de espaço.

- [x] Utilizar loggings no lugar de prints e um logging após a mensagem "Então o seu tipo de pokémon favorito é ...?! Pode deixar!"  para que o usuário siba que está em execução o código.

- [x] Tratar o erro da linha 113 (Que erro é? Eu usuário não sei XD)

- [x] Na linha 110, fiz um teste trocando "type == json['data']['getPokemon']['types'][0]"  para
"type in json['data']['getPokemon']['types']"  (checando se existe dentro do campo "types" em todas as posições disponíveis)
de 91 me retornou 95 pokemons, aparentemente há pokemons do tipo normal que a posição é outra nesse campo.

- [x] O retorno do json é bem completo, da pra ajustar o write pra trazer bem completinho as info do pokemon

- [x] add README e requirements

- [x] Dividir responsabilidades

**Comment by ViniciusII** [comment]
Obrigado pelas recomendações Ataíde! Já estou trabalhando nessas alterações!! Em breve você poderá conferir a nova versão do código!
